fix: replace isDeprecated with isRemoved
serverpod/serverpod pull request #2248
Opened 2024-05-14 07:25 UTC by klkucaj

## Pre-launch Checklist

- [ ] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [ ] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [ ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

2024-05-15 10:18 UTC, SandPod requested changes
Didn't finish the full review but I need you to take a closer look at what was actually deprecated and remove test related to this along with other functinality that is not needed.

2024-05-15 14:57 UTC, klkucaj commented on tools/serverpod_cli/lib/src/analyzer/models/yaml_definitions/class_yaml_definition.dart
>                ),
Its on line 74 now with the new update, should i remove it at all ?

2024-05-16 08:20 UTC, SandPod commented on tools/serverpod_cli/lib/src/analyzer/models/yaml_definitions/class_yaml_definition.dart
>                ),
No, if it is used in another validation rule it should not be removed

2024-05-16 08:30 UTC, SandPod requested changes
There are still reduntant tests connected to the removed keywords.

Please look at the complete diff of the PR and all tests you touched and ensure actually validate something.

2024-05-16 08:30 UTC, SandPod commented on tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_parent_test.dart
> -
chore: This file still contains a bunch of tests that are not required anymore. Please remove all tests except maybe a single one that validates that the parent keyword generates an error deprecation warning.

You have basically removed the expects from all tests in the file that make them unique, so we are just validating the same thing over and over again.

2024-05-16 08:30 UTC, SandPod commented on tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_persist_test.dart
> +      expect(collector.errors.length, 1);
chore: this test is reduntant remove it. Please check all other tests. We don't have any mutually exclusivity anymore so there is nothing to validate.

2024-05-16 14:41 UTC, SandPod approved these changes
Looks good! Nice to get rid of the deprecations and good job navigating the test changes 🚀

2024-05-16 14:46 UTC, merged