create and use SignInWithEmailDialogLabels
serverpod/serverpod pull request #2391
Opened 2024-06-16 07:57 UTC by BenAuerDev

This PR adds the functionality to localize/internationalize the labels in the `SignInWithEmailDialog`.

The `SignInWithEmailButton` now accepts a (nullable) parameter `labels` of type `SignInWithEmailLabels` consisting of nullable Strings.

![signin-spanish](https://github.com/serverpod/serverpod/assets/136239531/215c12e6-a3be-4c22-add3-235152e4846e)

When passed with valid strings this shows in the UI: 

![spanish-log-in](https://github.com/serverpod/serverpod/assets/136239531/c7113138-7be4-4e4e-a30b-88423ca44259)

If a individual String is `null`, the english fallback is used.

![auth-half-spanish](https://github.com/serverpod/serverpod/assets/136239531/5aea59e6-1a7f-44b2-8b7a-dd9dc46a0e68)

As the validation message has a variable in the middle i split it into 
`minimum` and `characters` 
But only show the custom label if both are present

```dart
_passwordIssue = widget.labels?.minimum != null &&
                widget.labels?.characters != null
            ? '${widget.labels?.minimum} ${widget.minPasswordLength} ${widget.labels?.characters}'
            : 'Minimum ${widget.minPasswordLength} characters';
```

I also thought about adding an assertion to `SignInWithEmailLabels` informing the user that "All or none of minimum, maximum and characters needs to be provided". But was not sure if that isn't too much.

```dart
    this.enterCode,
    this.incorrectCode,
    this.incorrectPassword,
  }) : assert(
          // Check that all or none of the minimum, maximum and characters are provided.
          (minimum == null && maximum == null && characters == null) ||
              (minimum != null && maximum != null && characters != null),
          'All or none of minimum, maximum and characters must be provided.',
        );
}

```

I can of course add it anytime

closes #2291 

## Pre-launch Checklist

- [ ] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [ ] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [ ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

no breaking changes

2024-07-11 06:29 UTC, SandPod commented
This makes sense to me; it allows us to be unopinionated about what localization package you might be using.
@Isakdl had a couple of comments around naming that he will get back to you on 👍  (He has more flutter development experience than me)

2024-09-07 19:12 UTC, Aygistov commented
It would be very useful!

2025-02-25 10:38 UTC, Isakdl requested changes
@BenAuerDev Thank you for the PR and I'm sorry for the very delayed review! 

I have made some suggestions but I. like the general idea of where we are going with this :)

2025-02-25 10:38 UTC, Isakdl commented on modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_dialog.dart
> +            ? '${widget.labels?.minimum} ${widget.minPasswordLength} ${widget.labels?.characters}'
Comment: The problem with this type of contamination is that it may not work for all languages. When doing plurality and numbers i18n packages normally have a callback of some kind and give you the number so you can template the string however you want. 

Suggestion: I think it is likely a better idea to make this a callback that takes the minPasswordLength and expects the full string back. Instead of "minimum" and "characters".

2025-02-25 10:38 UTC, Isakdl commented on modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_button.dart
> +    this.labels,
Suggestion: Rename this to `localization`.

2025-02-25 10:38 UTC, Isakdl commented on modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_labels.dart
> +    this.incorrectPassword,
Suggestion: I think it would be nice to give these names some more context to what they are modifying. Such as "resetPassword" being the button title. "buttonTitleResetPassword".

This way it becomes easier to deduce where each of these texts are used. I would also suggest expanding the docs comments to give more context on where the text is used.

2025-02-25 10:38 UTC, Isakdl commented on modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_labels.dart
> +class SignInWithEmailDialogLabels {
Suggestion: I also think it may make more sense to move the default values into this file instead of inlining it!

But doing so I think we would need a copyWith method on this class to allow for easy modifications of singular fields.

2025-02-27 08:57 UTC, BenAuerDev commented on modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_labels.dart
> +class SignInWithEmailDialogLabels {
Good point, my initial thought why I inlined the default values was to make it easier to see which field you're looking at in signin_dialog.dart. 

![Selection_035](https://github.com/user-attachments/assets/fe4a70fd-158e-488a-9fc0-34d685113511)

but I do admit, putting the default values in `SignInWithEmailDialogLabels` is cleaner :)

2025-03-03 16:25 UTC, Isakdl commented on modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_labels.dart
> +class SignInWithEmailDialogLabels {
Had some thinking around this.

I'm suggesting we do a factory constructor for the "default" perhaps call it `enUS`

In this constructor we set the all our variables as defaults but each of them can be overidden (optionally).

Then in the default constructor we set all variables as required without any defaults. This way we have a default that can easily be changed, but we still provide a constructor that helps you complete all variables for a new language. 

```dart

SignInWithEmailDialogLabels({
   required this.buttonTitleResetPassword,
   ...
});

SignInWithEmailDialogLabels.en({
   this.buttonTitleResetPassword = 'Rest Password',
   ...
});
```

2025-03-06 13:17 UTC, BenAuerDev commented on modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_dialog.dart
> +              'I have an account'),
This is used to navigate to the log in Screen 

![Selection_045](https://github.com/user-attachments/assets/c615246b-2753-4766-8680-55d24697a868)

`buttonTitleSignIn` is here for the "Sign In":

![Selection_046](https://github.com/user-attachments/assets/5e451506-53f3-45f0-95ac-bbcddd03c46b)

"Create Account" seems to be used for both navigating to the `create-account-page` and to submit the `form`

2025-03-10 09:52 UTC, Isakdl requested changes
Last little comment in the thread and we should be good to go :)

2025-03-10 17:10 UTC, Isakdl approved these changes
LGTM 🚀 🥳

2025-03-10 17:11 UTC, merged