feat: allow custom generation hash in AuthConfig
serverpod/serverpod pull request #2441
Opened 2024-07-05 15:46 UTC by Kiruel

Allow AuthConfig to take 2 more field:

`GeneratePasswordHashCallback` and `ValidatePasswordHashCallback` allow developer to choose their hashing process for the creation of the user or the validation of the user. Useful when migrate a database from another hashing process without re-create the password.

Fix https://github.com/serverpod/serverpod/issues/2440
## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

2024-07-05 15:47 UTC, Kiruel commented
I have read the CLA Document and I hereby sign the CLA

2024-07-08 09:53 UTC, SandPod requested changes
Thanks for posting this suggestion! 🎉 

This addition makes sense to me.

This PR is still missing tests assuring that the hash generation and validation can be correctly configured. Please add at least a sunny day scenario test.

We also need documentation for this before it can be merged added to our documentation repo, it think it makes sense to place it under https://docs.serverpod.dev/concepts/authentication/custom-overrides

2024-07-08 09:53 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart
> +    this.generatePasswordHashCallback,
Suggestion: Rename to `passwordHashGenerator` and `passwordHashValidator`.

This follows the pattern in the file for the rest of the callback methods, such as `userImageGenerator`.

2024-07-08 09:53 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart
> +  final ValidatePasswordHashCallback? validatePasswordHashCallback;
Suggestion: Make these non-nullable and always assign them to the default generator and validator.

No need to run a null check for these in runtime. We might as well always assign them to the default methods.

2024-07-08 09:53 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
> +      );
Suggestion: assign this directly in the auth configuration.

This removes a redundant null check here.

2024-07-08 09:53 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
> +    if (AuthConfig.current.validatePasswordHashCallback != null) {
Discussion/Question: How should we handle `onError` and `onValidationFailure` for the custom implementation?

2024-07-08 09:53 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
>        return await PasswordHash(
Suggestion: Assign this using the new interface as a callback to the config directly instead of branching inside of this method.

2024-07-09 06:45 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
> +    if (AuthConfig.current.validatePasswordHashCallback != null) {
That makes sense 👍

2024-07-09 06:51 UTC, SandPod reviewed
We still need tests that validate that this works as expected. I think these can be added here: https://github.com/serverpod/serverpod/blob/main/tests/serverpod_test_server/test_integration/authentication/email_auth_provider_test.dart

Also, please validate the interaction with the `Emails.tryMigrateAuthEntry` method so that your custom hashed passwords are not caught in any migration.

2024-07-09 06:51 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
> +      AuthConfig.current.passwordHashValidator(password, email, hash);
Chore: The onError and onValidationFailure are not being forwarded here.

2024-07-09 06:51 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart
> +typedef PasswordHashGenerator = Future<String> Function(String password);
Chore: add a note stating:  `Warning: Using a custom hashing algorithm for passwords will permanently disrupt compatibility with Serverpod's validation and password hash migration.`.

2024-07-09 10:29 UTC, Kiruel commented
I just try to build the integration testing on `main` branch but I got a fail test it's normal?

WIth `./util/run_tests_integration` fail at:

```bash
02:08 +584 -1: test_integration/database_operations/crud/delete_test.dart: Given an empty database when trying to delete a row that doesn't exist then an e
rror is thrown. [E]                         
tests_integration-serverpod_test_server-1  |   Expected: throws <Instance of 'DatabaseDeleteRowException'>
tests_integration-serverpod_test_server-1  |     Actual: <Instance of 'Future<SimpleData>'>
tests_integration-serverpod_test_server-1  |      Which: emitted _SimpleDataImpl:<{"id":1,"num":1}>
tests_integration-serverpod_test_server-1  |   
tests_integration-serverpod_test_server-1  |   package:test_api  OutstandingWork.complete
tests_integration-serverpod_test_server-1  |   
tests_integration-serverpod_test_server-1  | 
tests_integration-serverpod_test_server-1  | To run this test again: dart test test_integration/database_operations/crud/delete_test.dart -p vm --plain-nam
e 'Given an empty database when trying to delete a row that doesn'\''t exist then an error is thrown.'

```

2024-07-10 07:09 UTC, SandPod commented
> I just try to build the integration testing on `main` branch but I got a fail test it's normal @SandPod ?
> 
> With `./util/run_tests_integration` fail at:
> ....

Hmm, no, this should not be the case. It seems like there might be a bad cleanup going on there, but this should also show in our actions on gitub for main. Is there a possibility that you might have missed cleaning up the database properly after the tests are finished? (It could also be something that we have introduced).

> And another thing, I could not find the file `./setup-tables` to test one individual test from the doc here: https://docs.serverpod.dev/contribute#running-individual-tests

Unfortunately, that documentation is outdated. Starting the test server with the `--apply-migrations` flag is enough to set the database up to run the tests. The individual tests will create any database entries that they require.

Will try to update the docs over the next few days.

2024-07-10 08:39 UTC, Kiruel commented
I will delete the database test then re-start the tests and tell you if I still got the error. Anyway I just push the integration test for the AuthConfig.

2024-07-10 09:37 UTC, Kiruel commented
After docker rm the test container and re-start the test on main still got the error.

2024-07-11 06:41 UTC, SandPod commented
When investigating a file, we fixed a flaky test there 2 weeks ago. Have you merged the latest main into your branch? If not, the fix for the flaky test might not be there.

When GitHub runs actions, it actually merges your branch with the main and then runs the actions, so that might be the reason the test failure is not showing up in the test runner.

Another theory could be that there are more flaky tests in that file that we have not triggered yet.

2024-07-11 06:56 UTC, SandPod commented on tests/serverpod_test_server/test_integration/authentication/email_auth_provider_test.dart
> +  group('Given create account request without hashing generator', () {
Suggestion: Please also add a test validating that our password migration isn't triggered if any of these are set.

2024-07-11 06:56 UTC, SandPod commented on tests/serverpod_test_server/test_integration/authentication/email_auth_provider_test.dart
> +  group('Given create account request without hashing generator', () {
For example, Given custom hash generator and a stored legacy password in the database when user is authenticating then password is not migrated.

2024-07-11 06:56 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
> +      var migratedAuth = await Emails.tryMigrateAuthEntry(
Suggestion: add a similar guard to the `migrateLegacyPasswordHashes` method but with a throw instead.

Also add the following documentation to the method: Warning: This migration method is designed for password hashes generated by the framework's default algorithm. Hashes stored with a custom generator or different algorithm may produce unexpected results.

2024-07-11 09:10 UTC, Kiruel commented
> When investigating a file, we fixed a flaky test there 2 weeks ago. Have you merged the latest main into your branch? If not, the fix for the flaky test might not be there.
> 
> When GitHub runs actions, it actually merges your branch with the main and then runs the actions, so that might be the reason the test failure is not showing up in the test runner.
> 
> Another theory could be that there are more flaky tests in that file that we have not triggered yet.

Yes I pull the lastest main when I got the fail test.

2024-07-22 09:37 UTC, SandPod requested changes
PR looks good to me now!

Please ensure that you have the documentation ready before we merge this.

2024-07-22 09:37 UTC, SandPod commented on modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
> +    }
Suggestion: Change to `Legacy password hash migration not supported when using custom password hash algorithm.`

2024-07-25 22:30 UTC, Kiruel commented
Adding documentation on this PR https://github.com/serverpod/serverpod_docs/pull/130

2024-08-05 07:44 UTC, SandPod approved these changes
LGTM! 👍

2024-08-05 07:45 UTC, merged