fix: Fixing 'toJsonForProtocol' method call for custom classes
serverpod/serverpod pull request #3015
Opened 2024-12-03 12:52 UTC by klkucaj

### PR Description:

This PR improves the `toJsonForProtocol` method by adding runtime checks to correctly handle custom classes. It ensures that the appropriate serialization method is invoked dynamically.

Closes: [2977](https://github.com/serverpod/serverpod/issues/2977)

## Pre-launch Checklist

- [ ] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [ ] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [ ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

_If you have done any breaking changes, make sure to outline them here, so that they can be included in the notes for the next release._

2024-12-04 09:24 UTC, SandPod requested changes
Couple of suggestion but I'm also missing tests.

2024-12-04 09:24 UTC, SandPod commented on tests/serverpod_test_server/lib/src/custom_classes.dart
> +class CustomClass3 implements SerializableModel {
Suggestion: We should have a model field that uses ProtocolSerialization as well.

Add a test that calls this model to validate that the toJsonForProtcol value is retrieved.

2024-12-04 09:24 UTC, SandPod commented on tests/serverpod_test_server/lib/src/custom_classes.dart
>    String toJsonForProtocol() => value;
Suggestion: Remove toJsonForProtocol implementation if the interface is not implemented by this class.

We should have examples of both used as fields.

2024-12-04 09:24 UTC, SandPod commented on tools/serverpod_cli/lib/src/generator/dart/library_generators/model_library_generator.dart
> +    if (fieldType.customClass && toJsonMethodName == 'toJsonForProtocol') {
Sugggestion: Create enums (or constant variables) for `'toJsonForProtocol'` so that we only have a single definition of it.

2024-12-04 09:24 UTC, SandPod commented on tools/serverpod_cli/test/generator/dart/server_code_generator/custom_class_test.dart
> +            '}';
Suggestion: Break out this to multiple expects for different parts of the code.

The expect here will be to sensitive to change. If the "style" changes this test might fail for irrelevant reasons. Please validate the important parts separately with different expects.

2024-12-04 09:24 UTC, SandPod commented on tools/serverpod_cli/test/generator/dart/server_code_generator/custom_class_test.dart
> +            '}';
Could also be different "tests" to slim down what each expect is testing.

2024-12-05 08:52 UTC, klkucaj commented
@SandPod pr is ready!

2024-12-05 11:14 UTC, SandPod commented on tests/serverpod_test_server/lib/src/custom_classes.dart
> +/// Custom class that does not implement ProtocolSerialization.
Suggestion: Remove redundant comment.

This is already implied by the name of this and the next class but you can keep the comment for clarification on the last one.

2024-12-05 11:14 UTC, SandPod commented on tests/serverpod_test_client/lib/src/custom_classes.dart
> +class CustomClassWithoutProtocolSerialization {
Suggestion: Make these a straight copy paste from the Server implementation.

This is most likely the scenario when our users are using custom classes.

2024-12-05 11:17 UTC, SandPod commented on tests/serverpod_test_server/lib/src/custom_classes.dart
> +  factory CustomClass.fromJson(dynamic data) {
Suggestion: For the class - Update the import in this class to `serverpod` instead of the `serverpod_client`.

2024-12-05 11:25 UTC, SandPod commented on tools/serverpod_cli/test/generator/dart/server_code_generator/custom_class_test.dart
> +        // This regex checks for this pattern:
Suggestion: `// This regex checks for this pattern but allows any number on the import.`

2024-12-05 11:27 UTC, SandPod commented on tools/serverpod_cli/lib/src/generator/dart/library_generators/model_library_generator.dart
> +const String _serverSideServerpodUrl = 'package:serverpod/serverpod.dart';
Suggestion: Use `serverpodUrl` instead.

This is already available there with the parameter set to `true`.

2024-12-05 12:33 UTC, klkucaj commented
@SandPod docs pr https://github.com/serverpod/serverpod_docs/pull/219

2024-12-05 14:40 UTC, SandPod approved these changes
LGTM given the last fixes.

2024-12-05 14:40 UTC, SandPod commented on tests/serverpod_test_shared/lib/src/custom_classes.dart
> +// system treats the two implementations this classes differently.
Suggestion: Remove comment

This is placed in a shared place now right?

2024-12-05 14:40 UTC, SandPod commented on tools/serverpod_cli/test/generator/dart/server_code_generator/custom_class_test.dart
> +        // his regex checks for this pattern but allows any number on the import.
Suggestion(NIT): This sentence starts with a typo.

2024-12-05 15:46 UTC, merged