Auth example improvement
serverpod/serverpod pull request #896
Opened 2023-05-09 09:56 UTC by Isakdl

# Changes

- Removes cyclic imports from the auth example flutter app and restructures the widgets in a folder
- Server side implementation of gmail with the help of mailer to show an example of sending an email

## Pre-launch Checklist

- [x ] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x ] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [ x] I listed at least one issue that this PR fixes in the description above.
- [x ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x ] All existing and new tests are passing.
- [ x] Any breaking changes are documented below.

2023-05-09 09:59 UTC, Isakdl commented
I have read the CLA Document and I hereby sign the CLA

2023-05-09 16:23 UTC, vlidholt requested changes
LGTM with minor nit fixed.

2023-05-09 16:23 UTC, vlidholt commented on examples/auth_example/auth_example_server/lib/server.dart
> +  // see https://support.google.com/accounts/answer/185833?hl=en for how to do that
Missing period at end of sentence.

2023-05-11 14:47 UTC, vlidholt approved these changes

2023-05-11 15:01 UTC, merged